/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package safeflyeu.view;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import safeflyeu.controller.ObradaAvioKompanija;
import safeflyeu.controller.ObradaKorisnik_AvioKompanija;
import safeflyeu.controller.ObradaOsiguranje;
import safeflyeu.controller.ObradaZaposlenik;
import safeflyeu.model.AvioKompanija;
import safeflyeu.model.Korisnik;
import safeflyeu.model.Korisnik_AvioKompanija;
import safeflyeu.model.Osiguranje;
import safeflyeu.model.Zaposlenik;
import safeflyeu.pomocno.SafeFlyEUException;

/**
 *
 * @author labak
 */
public class AvioKompanije extends javax.swing.JFrame {

    private final ObradaAvioKompanija obradaEntitet;
    
    private static DefaultComboBoxModel<Osiguranje> modelOsiguranje;
    private static DefaultComboBoxModel<Zaposlenik> modelZaposlenik;
    //private final ObradaKorisnik_AvioKompanija obradaKorisnik_AvioKompanija;
    private AvioKompanija avioKompanija;

    /**
     * Creates new form AvioKompanija
     */
    public AvioKompanije() {
        initComponents();
        obradaEntitet = new ObradaAvioKompanija();

        DefaultComboBoxModel<Osiguranje> os = new DefaultComboBoxModel<>();
        Osiguranje o = new Osiguranje();
        o.setId(0);
        o.setNaziv("Odaberite osiguranje");
        os.addElement(o);
        new ObradaOsiguranje().getLista().forEach((s) -> {
            os.addElement(s);
        });
        cmbOsiguranja.setModel(os);

        DefaultComboBoxModel<Zaposlenik> za = new DefaultComboBoxModel<>();
        Zaposlenik z = new Zaposlenik();
        z.setId(0);
        z.setIme("Odaberite zaposlenika");
        za.addElement(z);
        new ObradaZaposlenik().getLista().forEach((s) -> {
            za.addElement(s);
        });
        cmbZaposlenici.setModel(za);

        ucitajPodatke();
    }

    private void ucitajPodatke() {
        DefaultListModel<AvioKompanija> m = new DefaultListModel<>();

        obradaEntitet.getLista().forEach((ak) -> {
            m.addElement(ak);
        });

        lstEntiteti.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIban = new javax.swing.JTextField();
        txtLet = new javax.swing.JTextField();
        txtOib = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        txtNaziv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEntiteti = new javax.swing.JList<>();
        btnDodaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnPromjena = new javax.swing.JButton();
        txtAvion = new javax.swing.JTextField();
        btnBrisanje = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbOsiguranja = new javax.swing.JComboBox<>();
        cmbZaposlenici = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Avio-Kompanije");

        txtLet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLetKeyReleased(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lstEntiteti.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEntitetiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEntiteti);

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gill Sans Nova Ultra Bold", 1, 18)); // NOI18N
        jLabel1.setText("Avio-kompanija");

        jLabel2.setText("Naziv");

        jLabel3.setText("Osiguranje");

        jLabel5.setText("Iban");

        jLabel6.setText("Avion");

        jLabel7.setText("Let");

        jLabel8.setText("Oib");

        btnPromjena.setText("Promjena");
        btnPromjena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjenaActionPerformed(evt);
            }
        });

        txtAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvionActionPerformed(evt);
            }
        });

        btnBrisanje.setText("Brisanje");
        btnBrisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisanjeActionPerformed(evt);
            }
        });

        jLabel4.setText("Zaposlenik");

        cmbOsiguranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOsiguranjaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnDodaj)
                                        .addGap(27, 27, 27)
                                        .addComponent(btnPromjena))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(btnBrisanje))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cmbZaposlenici, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cmbOsiguranja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtAvion)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtIban)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtOib)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtNaziv)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4)
                                                .addComponent(txtLet, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBrisanje)
                            .addComponent(btnPromjena)
                            .addComponent(btnDodaj))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(txtLet, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIban, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOib, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbOsiguranja, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbZaposlenici, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(btnExit)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLetKeyReleased
        //if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        ucitajPodatke();
        // }
    }//GEN-LAST:event_txtLetKeyReleased

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
         AvioKompanija entitet = new AvioKompanija();

        preuzmiVrijednosti(entitet);

        try {
            obradaEntitet.save(entitet);
        } catch (SafeFlyEUException e) {
            JOptionPane.showConfirmDialog(null, e.getMessage());
            return;
        }

        ucitajPodatke();

        ocistiPolja();
//        AvioKompanija ak = new AvioKompanija();
//        ak = preuzmiVrijednosti(ak);
//        save(ak);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjenaActionPerformed
            AvioKompanija entitet = lstEntiteti.getSelectedValue();

        if (entitet == null) {
            JOptionPane.showConfirmDialog(null, "Prvo odaberite korisnika");
        }

        preuzmiVrijednosti(entitet);

        try {
            obradaEntitet.save(entitet);
        } catch (SafeFlyEUException e) {
            JOptionPane.showConfirmDialog(null, e.getMessage());
            return;
        }

        ucitajPodatke();

        ocistiPolja();
//        avioKompanija = lstEntiteti.getSelectedValue();
//        if (avioKompanija == null) {
//            JOptionPane.showMessageDialog(null, "Prvo odaberite avio kompaniju");
//            return;
//        }
//        try {
//            obradaEntitet.obrisi(avioKompanija);
//            ocistiPolja();
//            ucitajPodatke();
//        } catch (SafeFlyEUException e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
    }//GEN-LAST:event_btnPromjenaActionPerformed

    private void txtAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvionActionPerformed
        // TODO ad your handling code here:
    }//GEN-LAST:event_txtAvionActionPerformed

    private void btnBrisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisanjeActionPerformed
//        avioKompanija = lstEntiteti.getSelectedValue();
//        if (avioKompanija == null) {
//            JOptionPane.showMessageDialog(null, "Prvo odaberite avio kompaniju");
//            return;
//        }
//        try {
//            obradaEntitet.obrisi(avioKompanija);
//            ocistiPolja();
//            ucitajPodatke();
//        } catch (SafeFlyEUException e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }

        AvioKompanija entitet = lstEntiteti.getSelectedValue();

        if (entitet == null) {
            JOptionPane.showConfirmDialog(null, "Prvo odaberite korisnika");
        }

        try {
            obradaEntitet.obrisi(entitet);
            ucitajPodatke();
            ocistiPolja();
        } catch (SafeFlyEUException ex) {
            JOptionPane.showMessageDialog(null, "Ne mogu obrisati");
        }



    }//GEN-LAST:event_btnBrisanjeActionPerformed

    private void lstEntitetiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEntitetiValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        ocistiPolja();

        avioKompanija = lstEntiteti.getSelectedValue();

        if (avioKompanija == null) {
            return;
        }
        

//        if (evt.getValueIsAdjusting()) {
//            return;
//        }
//        ocistiPolja();
//
//        AvioKompanija entitet = lstEntiteti.getSelectedValue();
//
//        if (entitet == null) {
//            return;
//        }    

        txtNaziv.setText(avioKompanija.getNaziv());
        txtAvion.setText(avioKompanija.getAvion());
        txtIban.setText(avioKompanija.getIban());
        txtLet.setText(avioKompanija.getLet());
        txtOib.setText(avioKompanija.getOib());
        cmbOsiguranja.setSelectedItem(avioKompanija.getOsiguranje());
        cmbZaposlenici.setSelectedItem(avioKompanija.getZaposlenik());

//        preuzmiVrijednosti(ak);
        modelOsiguranje = (DefaultComboBoxModel<Osiguranje>) cmbOsiguranja.getModel();
        for (int i = 0; i < modelOsiguranje.getSize(); i++) {
            if (modelOsiguranje.getElementAt(i).getId() == avioKompanija.getOsiguranje().getId()) {
                cmbOsiguranja.setSelectedIndex(i);
                break;
            }
        }

        modelZaposlenik = (DefaultComboBoxModel<Zaposlenik>) cmbZaposlenici.getModel();
        for (int i = 0; i < modelZaposlenik.getSize(); i++) {
            if (modelZaposlenik.getElementAt(i).getId() == avioKompanija.getZaposlenik().getId()) {
                cmbZaposlenici.setSelectedIndex(i);
                break;
            }
        }
    }//GEN-LAST:event_lstEntitetiValueChanged

    private void cmbOsiguranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOsiguranjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOsiguranjaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanje;
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPromjena;
    private javax.swing.JComboBox<Osiguranje> cmbOsiguranja;
    private javax.swing.JComboBox<Zaposlenik> cmbZaposlenici;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<AvioKompanija> lstEntiteti;
    private javax.swing.JTextField txtAvion;
    private javax.swing.JTextField txtIban;
    private javax.swing.JTextField txtLet;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtOib;
    // End of variables declaration//GEN-END:variables

    private void ocistiPolja() {
        txtNaziv.setText("");
        cmbOsiguranja.setSelectedIndex(0);
        cmbZaposlenici.setSelectedIndex(0);
        txtAvion.setText("");
        txtLet.setText("");
        txtOib.setText("");
        txtIban.setText("");

    }

    private void save(AvioKompanija ak) {
        try {
            obradaEntitet.save(ak);
            ocistiPolja();
            ucitajPodatke();
        } catch (SafeFlyEUException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private AvioKompanija preuzmiVrijednosti(AvioKompanija ak) {
        ak.setNaziv(txtNaziv.getText());
        ak.setAvion(txtAvion.getText());
        ak.setIban(txtIban.getText());
        ak.setLet(txtLet.getText());
        ak.setOib(txtOib.getText());
        ak.getOsiguranje((Osiguranje) cmbOsiguranja.getSelectedItem());
        ak.getZaposlenik((Zaposlenik) cmbZaposlenici.getSelectedItem());
        
        return ak;

    }

//    private void save(AvioKompanija entitet) {
//        try {
//            obradaEntitet.save(entitet);
//            ocistiPolja();
//            ucitajPodatke();
//        } catch (SafeFlyEUException e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
//    }
}
